from django.urls import path, include  # Used to define and include URLs
from rest_framework import routers

# DRF’s built-in router system that automatically generates URL patterns for your viewsets
from .views import blogApiView, categoryApiView, categoryPostApiView

router = routers.SimpleRouter()
# Creates a router object using SimpleRouter that will handle API endpoints automatically

# Registers the viewsets with the router to generate appropriate URLs
router.register(
    "blogs", blogApiView, basename="blogs"
)  # Calls the blogApiView class when the user visits /blogs/. The basename is used to generate the URL name. It is optional. Not needed when blogApiView has a queryset attribute.
router.register("category", categoryApiView, basename="category")
router.register(
    "categoryBasedBlogs", categoryPostApiView, basename="categoryBasedBlogs"
)

urlpatterns = [
    path("", include(router.urls))
]  # Includes the URLs generated by the router in the urlpatterns list
